In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\Admin\Downloads\new_mpland.csv")

C:\Users\Admin\AppData\Local\Temp\ipykernel_9644\2037192879.py:1: DtypeWarning: Columns (0,1,2,4,5,6,7,10,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\Admin\Downloads\new_mpland.csv")

In [4]:
df.shape

(297472, 30)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297472 entries, 0 to 297471
Data columns (total 30 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Sr. No.                         297472 non-null  object
 1   Calamity Type                   13 non-null      object
 2   Calamity Name                   13 non-null      object
 3   Hon'ble Members of Parliament   296928 non-null  object
 4   Date of Consent                 13 non-null      object
 5   Consent Amount ( ₹ )            13 non-null      object
 6   Work Category                   33842 non-null   object
 7   Work                            194204 non-null  object
 8   State                           297459 non-null  object
 9   IDA                             296915 non-null  object
 10  Work Description                33763 non-null   object
 11  Constituency                    297459 non-null  object
 12  Image                           24539 non-null   object
 13  Completion Date                 33842 non-null   object
 14  Amount Disbursed ( ₹ )          33747 non-null   object
 15  Hon'ble Members of Parliaments  544 non-null     object
 16  Allocated AMOUNT ( ₹ )          543 non-null     object
 17  Work ID                         82367 non-null   object
 18  Expenditure Date                82367 non-null   object
 19  Vendor Name                     82367 non-null   object
 20  Payment Status                  82367 non-null   object
 21  Fund Disbursed Amount ( ₹ )     82367 non-null   object
 22  Work category                   180706 non-null  object
 23  Work description                180495 non-null  object
 24  Recommended date                180706 non-null  object
 25  Sanction Date                   155632 non-null  object
 26  Sanction Amount ( ₹ )           77995 non-null   object
 27  Work Status                     77995 non-null   object
 28  WORK                            102711 non-null  object
 29  RECOMMENDED AMOUNT   ( ₹ )      102711 non-null  object
dtypes: object(30)
memory usage: 68.1+ MB

In [6]:
print(df.columns.tolist())

['Sr. No.', 'Calamity Type', 'Calamity Name', "Hon'ble Members of Parliament", 'Date of Consent', 'Consent Amount ( ₹ )', 'Work Category', 'Work', 'State', 'IDA', 'Work Description', 'Constituency', 'Image', 'Completion Date', 'Amount Disbursed ( ₹ )', "Hon'ble Members of Parliaments", 'Allocated AMOUNT ( ₹ )', 'Work ID', 'Expenditure Date', 'Vendor Name', 'Payment Status', 'Fund Disbursed Amount ( ₹ )', 'Work category', 'Work description', 'Recommended date', 'Sanction Date', 'Sanction Amount ( ₹ )', 'Work Status', 'WORK', 'RECOMMENDED AMOUNT   ( ₹ )']

In [7]:
# Convert Work description to lowercase and remove extra spaces
df['Work description'] = df['Work description'].str.lower().str.strip()

# Convert Work category to lowercase and remove extra spaces
df['Work category'] = df['Work category'].str.lower().str.strip()

In [8]:
df.sample(5)

,Sr. No.,Calamity Type,Calamity Name,Hon'ble Members of Parliament,Date of Consent,Consent Amount ( ₹ ),Work Category,Work,State,IDA,...,Payment Status,Fund Disbursed Amount ( ₹ ),Work category,Work description,Recommended date,Sanction Date,Sanction Amount ( ₹ ),Work Status,WORK,RECOMMENDED AMOUNT ( ₹ )
178104,61339,NaN,NaN,Jagdambika Pal,NaN,NaN,NaN,WS/MP791/2025-2026/252164-Construction of road...,Uttar Pradesh,Siddharthnagar(DISTRICT MAGISTRATE SIDDHARTH N...,...,NaN,NaN,normal/others,amaa nankar me pwd road se prahlad ke gahr hot...,05-Dec-2025,24-Jan-2026,1750000.0,Sanction,NaN,NaN
3640,3628,NaN,NaN,CHAMALA KIRAN KUMAR REDDY,NaN,NaN,Normal/Others,WS/MP18338/2024-2025/149812-Street lights,Telangana,RANGA REDDY(DISTRICT COLLECTOR RANGAREDDY_IDA),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39679,5281,NaN,NaN,SAGAR ESHWAR KHANDRE,NaN,NaN,NaN,Construction of community centers and communit...,Karnataka,BIDAR(DEPUTY COMMISSIONER BIDAR_IDA),...,Payment Success,371250.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96669,62271,NaN,NaN,RAJA RAM SINGH,NaN,NaN,NaN,Providing drains and gutters for public drainage,Bihar,AURANGABAD(DISTRICT PLANNING OFFICER AURANGABA...,...,Payment Success,197102.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181022,64257,NaN,NaN,Smt Sandhya Ray,NaN,NaN,NaN,WS/\t MP655/2025-2026/258267-Installation of f...,Madhya Pradesh,BHIND(DISTRICT COLLECTOR BHIND_IDA),...,NaN,NaN,normal/others,open gym for public health system 12 equipment...,09-Jan-2026,16-Feb-2026,772290.0,Work partially Completed,NaN,NaN

In [9]:
# Convert Recommended date into datetime format
df['Recommended date'] = pd.to_datetime(df['Recommended date'], errors='coerce')

# Convert Sanction Date into datetime format
df['Sanction Date'] = pd.to_datetime(df['Sanction Date'], errors='coerce')

# Convert Completion Date into datetime format
df['Completion Date'] = pd.to_datetime(df['Completion Date'], errors='coerce')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297472 entries, 0 to 297471
Data columns (total 30 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Sr. No.                         297472 non-null  object
 1   Calamity Type                   13 non-null      object
 2   Calamity Name                   13 non-null      object
 3   Hon'ble Members of Parliament   296928 non-null  object
 4   Date of Consent                 13 non-null      object
 5   Consent Amount ( ₹ )            13 non-null      object
 6   Work Category                   33842 non-null   object
 7   Work                            194204 non-null  object
 8   State                           297459 non-null  object
 9   IDA                             296915 non-null  object
 10  Work Description                33763 non-null   object
 11  Constituency                    297459 non-null  object
 12  Image                           24539 non-null   object
 13  Completion Date                 33841 non-null   datetime64[ns]
 14  Amount Disbursed ( ₹ )          33747 non-null   object
 15  Hon'ble Members of Parliaments  544 non-null     object
 16  Allocated AMOUNT ( ₹ )          543 non-null     object
 17  Work ID                         82367 non-null   object
 18  Expenditure Date                82367 non-null   object
 19  Vendor Name                     82367 non-null   object
 20  Payment Status                  82367 non-null   object
 21  Fund Disbursed Amount ( ₹ )     82367 non-null   object
 22  Work category                   180706 non-null  object
 23  Work description                180495 non-null  object
 24  Recommended date                180704 non-null  datetime64[ns]
 25  Sanction Date                   155630 non-null  datetime64[ns]
 26  Sanction Amount ( ₹ )           77995 non-null   object
 27  Work Status                     77995 non-null   object
 28  WORK                            102711 non-null  object
 29  RECOMMENDED AMOUNT   ( ₹ )      102711 non-null  object
dtypes: datetime64[ns](3), object(27)
memory usage: 68.1+ MB

In [11]:
print(df[['Constituency', 'Work description', 'Sanction Amount ( ₹ )']].head())

  Constituency Work description Sanction Amount ( ₹ )
0          NaN              NaN                   NaN
1          NaN              NaN                   NaN
2          NaN              NaN                   NaN
3          NaN              NaN                   NaN
4          NaN              NaN                   NaN

In [12]:
print(df[['Constituency', 'Work description', 'Sanction Amount ( ₹ )']].notna().sum())

Constituency             297459
Work description         180495
Sanction Amount ( ₹ )     77995
dtype: int64

In [13]:
matching_data = df[
    df['Constituency'].notna() &
    df['Work description'].notna() &
    df['Sanction Amount ( ₹ )'].notna()
]

print(matching_data.shape)

(77897, 30)

In [14]:
matching_data = df[
    df['Constituency'].notna() &
    df['Work description'].notna() &
    df['Sanction Amount ( ₹ )'].notna()
].copy()

In [15]:
# Normalize Constituency
matching_data['Constituency_clean'] = (
    matching_data['Constituency'].astype(str).str.lower().str.strip()
)

# Normalize Work description
matching_data['Work_description_clean'] = (
    matching_data['Work description'].astype(str).str.lower().str.strip()
)

# Normalize Sanction Amount
matching_data['Sanction_Amount_clean'] = (
    matching_data['Sanction Amount ( ₹ )']
    .astype(str)
    .str.replace(',', '', regex=False)
    .str.strip()
)

In [16]:
matching_data['Project_ID'] = (
    matching_data['Constituency_clean'] + '_' +
    matching_data['Work_description_clean'] + '_' +
    matching_data['Sanction_Amount_clean']
)

In [17]:
matching_data[['Constituency', 'Work description',
               'Sanction Amount ( ₹ )', 'Project_ID']].head()

,Constituency,Work description,Sanction Amount ( ₹ ),Project_ID
116766,DHARWAD,construction of community bhavan at navalgund ...,497185.0,dharwad_construction of community bhavan at na...
116767,DHARWAD,construction of college room of cbs charitabl...,500000.0,dharwad_construction of college room of cbs c...
116768,DHARWAD,construction of community bhavan of veerashaiv...,450000.0,dharwad_construction of community bhavan of ve...
116769,DHARWAD,construction of maremma cultural bhavan at nee...,1500000.0,dharwad_construction of maremma cultural bhava...
116770,DHARWAD,construction of cultural bhavan at kundagol tq...,398009.0,dharwad_construction of cultural bhavan at kun...

In [18]:
matching_data['Sanction_Amount_clean'] = (
    pd.to_numeric(matching_data['Sanction Amount ( ₹ )'], errors='coerce')
    .fillna(0)
    .astype(int)
    .astype(str)
)

In [19]:
matching_data['Project_ID'] = (
    matching_data['Constituency_clean'] + '_' +
    matching_data['Work_description_clean'] + '_' +
    matching_data['Sanction_Amount_clean']
)

In [20]:
matching_data[['Constituency', 'Work description',
               'Sanction Amount ( ₹ )', 'Project_ID']].head()

,Constituency,Work description,Sanction Amount ( ₹ ),Project_ID
116766,DHARWAD,construction of community bhavan at navalgund ...,497185.0,dharwad_construction of community bhavan at na...
116767,DHARWAD,construction of college room of cbs charitabl...,500000.0,dharwad_construction of college room of cbs c...
116768,DHARWAD,construction of community bhavan of veerashaiv...,450000.0,dharwad_construction of community bhavan of ve...
116769,DHARWAD,construction of maremma cultural bhavan at nee...,1500000.0,dharwad_construction of maremma cultural bhava...
116770,DHARWAD,construction of cultural bhavan at kundagol tq...,398009.0,dharwad_construction of cultural bhavan at kun...

In [21]:
import sys
print(sys.executable)

C:\ProgramData\anaconda3\python.exe

In [22]:
import sys
!{sys.executable} -m pip install rapidfuzz

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: rapidfuzz in c:\users\admin\appdata\roaming\python\python313\site-packages (3.14.5)

In [23]:
from rapidfuzz import fuzz

print("RapidFuzz working!")

RapidFuzz working!

In [24]:
print("Total rows:", len(matching_data))
print("Unique Project IDs:", matching_data['Project_ID'].nunique())
print("Duplicate Project IDs:", matching_data['Project_ID'].duplicated().sum())

Total rows: 77897
Unique Project IDs: 71796
Duplicate Project IDs: 6101

In [25]:
duplicates = matching_data[
    matching_data['Project_ID'].duplicated(keep=False)
]

print(duplicates.shape)

(7143, 34)

In [26]:
duplicates[['Constituency', 'Work description',
            'Sanction Amount ( ₹ )', 'Project_ID']].head(20)

,Constituency,Work description,Sanction Amount ( ₹ ),Project_ID
117266,KALAHANDI,"obstetric delivery table, wheel chair folding,...",500000.0,"kalahandi_obstetric delivery table, wheel chai..."
117267,KALAHANDI,"obstetric delivery table, wheel chair folding,...",500000.0,"kalahandi_obstetric delivery table, wheel chai..."
117268,KALAHANDI,"obstetric delivery table, wheel chair folding,...",500000.0,"kalahandi_obstetric delivery table, wheel chai..."
117269,KALAHANDI,"obstetric delivery table, wheel chair folding,...",499500.0,"kalahandi_obstetric delivery table, wheel chai..."
117270,KALAHANDI,"obstetric delivery table, wheel chair folding,...",499500.0,"kalahandi_obstetric delivery table, wheel chai..."
117271,KALAHANDI,"obstetric delivery table, wheel chair folding,...",499500.0,"kalahandi_obstetric delivery table, wheel chai..."
117272,KALAHANDI,"obstetric delivery table, wheel chair folding,...",499500.0,"kalahandi_obstetric delivery table, wheel chai..."
117273,KALAHANDI,"obstetric delivery table, wheel chair folding,...",500000.0,"kalahandi_obstetric delivery table, wheel chai..."
117274,KALAHANDI,"obstetric delivery table, wheel chair folding,...",500000.0,"kalahandi_obstetric delivery table, wheel chai..."
117289,ROHTAK,development works in harijan choupal,500000.0,rohtak_development works in harijan choupal_50...
117331,KHANDWA,purchase of books for students intellectual de...,100000.0,khandwa_purchase of books for students intelle...
117332,KHANDWA,purchase of books for students intellectual de...,100000.0,khandwa_purchase of books for students intelle...
117333,KHANDWA,purchase of books for students intellectual de...,100000.0,khandwa_purchase of books for students intelle...
117334,KHANDWA,purchase of books for students intellectual de...,100000.0,khandwa_purchase of books for students intelle...
117335,KHANDWA,purchase of books for students intellectual de...,100000.0,khandwa_purchase of books for students intelle...
117336,KHANDWA,purchase of books for students intellectual de...,100000.0,khandwa_purchase of books for students intelle...
117337,KHANDWA,purchase of books for students intellectual de...,100000.0,khandwa_purchase of books for students intelle...
117338,KHANDWA,purchase of books for students intellectual de...,100000.0,khandwa_purchase of books for students intelle...
117354,KHANDWA,high mask solar lights,445200.0,khandwa_high mask solar lights_445200
117355,KHANDWA,high mask solar lights,445200.0,khandwa_high mask solar lights_445200

In [27]:
print(df.columns.tolist())

['Sr. No.', 'Calamity Type', 'Calamity Name', "Hon'ble Members of Parliament", 'Date of Consent', 'Consent Amount ( ₹ )', 'Work Category', 'Work', 'State', 'IDA', 'Work Description', 'Constituency', 'Image', 'Completion Date', 'Amount Disbursed ( ₹ )', "Hon'ble Members of Parliaments", 'Allocated AMOUNT ( ₹ )', 'Work ID', 'Expenditure Date', 'Vendor Name', 'Payment Status', 'Fund Disbursed Amount ( ₹ )', 'Work category', 'Work description', 'Recommended date', 'Sanction Date', 'Sanction Amount ( ₹ )', 'Work Status', 'WORK', 'RECOMMENDED AMOUNT   ( ₹ )']

In [28]:
#records belongs to each
print("Recommended:", df['Recommended date'].notna().sum())
print("Sanctioned:", df['Sanction Date'].notna().sum())
print("Expenditure:", df['Expenditure Date'].notna().sum())
print("Completed:", df['Completion Date'].notna().sum())

Recommended: 180704
Sanctioned: 155630
Expenditure: 82367
Completed: 33841

In [29]:
df['Project Stage'] = 'Recommended'

df.loc[df['Sanction Date'].notna(), 'Project Stage'] = 'Sanctioned'

df.loc[df['Expenditure Date'].notna(), 'Project Stage'] = 'Expenditure'

df.loc[df['Completion Date'].notna(), 'Project Stage'] = 'Completed'

In [30]:
print(df['Project Stage'].value_counts())

Project Stage
Sanctioned     155630
Expenditure     82367
Completed       33841
Recommended     25634
Name: count, dtype: int64

In [31]:
# Create clean matching fields
df['Constituency_clean'] = (
    df['Constituency']
    .astype(str)
    .str.lower()
    .str.strip()
)

df['Work_description_clean'] = (
    df['Work description']
    .astype(str)
    .str.lower()
    .str.strip()
)

df['Sanction_Amount_clean'] = (
    pd.to_numeric(
        df['Sanction Amount ( ₹ )'],
        errors='coerce'
    )
    .fillna(0)
    .astype(int)
    .astype(str)
)

In [32]:

mask = (
    df['Constituency'].notna() &
    df['Work description'].notna() &
    df['Sanction Amount ( ₹ )'].notna()
)

df.loc[mask, 'Project_ID'] = (
    df.loc[mask, 'Constituency_clean'] + '_' +
    df.loc[mask, 'Work_description_clean'] + '_' +
    df.loc[mask, 'Sanction_Amount_clean']
)

In [33]:
df[['Constituency', 'Work description',
           'Sanction Amount ( ₹ )', 'Project_ID',
           'Project Stage']].head(10)

  Constituency Work description Sanction Amount ( ₹ ) Project_ID Project Stage
0          NaN              NaN                   NaN        NaN   Recommended
1          NaN              NaN                   NaN        NaN   Recommended
2          NaN              NaN                   NaN        NaN   Recommended
3          NaN              NaN                   NaN        NaN   Recommended
4          NaN              NaN                   NaN        NaN   Recommended
5          NaN              NaN                   NaN        NaN   Recommended
6          NaN              NaN                   NaN        NaN   Recommended
7          NaN              NaN                   NaN        NaN   Recommended
8          NaN              NaN                   NaN        NaN   Recommended
9          NaN              NaN                   NaN        NaN   Recommended

In [34]:
df[['Constituency', 'Work description',
           'Sanction Amount ( ₹ )', 'Project_ID',
           'Project Stage']].head(20)

,Constituency,Work description,Sanction Amount ( ₹ ),Project_ID,Project Stage
0,NaN,NaN,NaN,NaN,Recommended
1,NaN,NaN,NaN,NaN,Recommended
2,NaN,NaN,NaN,NaN,Recommended
3,NaN,NaN,NaN,NaN,Recommended
4,NaN,NaN,NaN,NaN,Recommended
5,NaN,NaN,NaN,NaN,Recommended
6,NaN,NaN,NaN,NaN,Recommended
7,NaN,NaN,NaN,NaN,Recommended
8,NaN,NaN,NaN,NaN,Recommended
9,NaN,NaN,NaN,NaN,Recommended
10,NaN,NaN,NaN,NaN,Recommended
11,NaN,NaN,NaN,NaN,Recommended
12,NaN,NaN,NaN,NaN,Recommended
13,ARARIA,NaN,NaN,NaN,Completed
14,FARIDKOT(SC),NaN,NaN,NaN,Completed
15,KOLLAM,NaN,NaN,NaN,Completed
16,FARIDKOT(SC),NaN,NaN,NaN,Completed
17,FARIDKOT(SC),NaN,NaN,NaN,Completed
18,FARIDKOT(SC),NaN,NaN,NaN,Completed
19,KOLLAM,NaN,NaN,NaN,Completed

In [35]:
# Remove the old incorrect Project_ID
df['Project_ID'] = pd.NA

# Create Project_ID only when all 3 fields are available
mask = (
    df['Constituency'].notna() &
    df['Work description'].notna() &
    df['Sanction Amount ( ₹ )'].notna()
)

df.loc[mask, 'Project_ID'] = (
    df.loc[mask, 'Constituency_clean'] + '_' +
    df.loc[mask, 'Work_description_clean'] + '_' +
    df.loc[mask, 'Sanction_Amount_clean']
)

In [36]:
df[['Constituency',
           'Work description',
           'Sanction Amount ( ₹ )',
           'Project_ID',
           'Project Stage']].head(20)

,Constituency,Work description,Sanction Amount ( ₹ ),Project_ID,Project Stage
0,NaN,NaN,NaN,<NA>,Recommended
1,NaN,NaN,NaN,<NA>,Recommended
2,NaN,NaN,NaN,<NA>,Recommended
3,NaN,NaN,NaN,<NA>,Recommended
4,NaN,NaN,NaN,<NA>,Recommended
5,NaN,NaN,NaN,<NA>,Recommended
6,NaN,NaN,NaN,<NA>,Recommended
7,NaN,NaN,NaN,<NA>,Recommended
8,NaN,NaN,NaN,<NA>,Recommended
9,NaN,NaN,NaN,<NA>,Recommended
10,NaN,NaN,NaN,<NA>,Recommended
11,NaN,NaN,NaN,<NA>,Recommended
12,NaN,NaN,NaN,<NA>,Recommended
13,ARARIA,NaN,NaN,<NA>,Completed
14,FARIDKOT(SC),NaN,NaN,<NA>,Completed
15,KOLLAM,NaN,NaN,<NA>,Completed
16,FARIDKOT(SC),NaN,NaN,<NA>,Completed
17,FARIDKOT(SC),NaN,NaN,<NA>,Completed
18,FARIDKOT(SC),NaN,NaN,<NA>,Completed
19,KOLLAM,NaN,NaN,<NA>,Completed

In [37]:
df[df['Project_ID'].notna()
][['Constituency',
   'Work description',
   'Sanction Amount ( ₹ )',
   'Project_ID',
   'Project Stage']].head(10)

,Constituency,Work description,Sanction Amount ( ₹ ),Project_ID,Project Stage
116766,DHARWAD,construction of community bhavan at navalgund ...,497185.0,dharwad_construction of community bhavan at na...,Sanctioned
116767,DHARWAD,construction of college room of cbs charitabl...,500000.0,dharwad_construction of college room of cbs c...,Sanctioned
116768,DHARWAD,construction of community bhavan of veerashaiv...,450000.0,dharwad_construction of community bhavan of ve...,Sanctioned
116769,DHARWAD,construction of maremma cultural bhavan at nee...,1500000.0,dharwad_construction of maremma cultural bhava...,Sanctioned
116770,DHARWAD,construction of cultural bhavan at kundagol tq...,398009.0,dharwad_construction of cultural bhavan at kun...,Sanctioned
116771,DHARWAD,construction of community hall at uppinbetager...,399104.0,dharwad_construction of community hall at uppi...,Sanctioned
116772,DHARWAD,construction of community hall at shibargatti ...,396154.0,dharwad_construction of community hall at shib...,Sanctioned
116773,DHARWAD,construction of community hall at hosategur vi...,400000.0,dharwad_construction of community hall at hosa...,Sanctioned
116774,DHARWAD,construction of community hall at kardigudda v...,495627.0,dharwad_construction of community hall at kard...,Sanctioned
116775,DHARWAD,construction of community hall at tadakod vill...,398955.0,dharwad_construction of community hall at tada...,Sanctioned

In [38]:
# Check number of unique projects
print("Unique Project IDs:", df['Project_ID'].nunique())

# Check rows available for matching
print("Rows with Project ID:", df['Project_ID'].notna().sum())

Unique Project IDs: 71796
Rows with Project ID: 77897

In [39]:
# Check duplicate Project IDs
print(
    df['Project_ID']
    .value_counts()
    .head(10)
)

Project_ID
puri_installation of solar light at creamation ground._40000                                                                 178
nagina(sc)_high mast light with four led recommended in my constituency nagina by implemneting agency pccd bijnore_106900    128
nagina(sc)_high mast light with four led recommended in my constituency nagina by implemneting agency pccd bijnore_106850    118
jalaun(sc)_ms pole with led semi high mast light_243000                                                                      115
tikamgarh(sc)_muktidham nirman_207638                                                                                        109
jamui(sc)_purchase of book shelf for school and college_249990                                                                80
mandsour_purchase of books_100000                                                                                             74
raiganj_proposed model plan for the construction of cremation chully along with small rest shade_500000                       73
hisar_new water tanker for panchayat_165000                                                                                   70
nandurbar(st)_install 2 set of street lights_170000                                                                           66
Name: count, dtype: int64

In [40]:
fuzzy_data = df[
    df['Constituency'].notna() &
    df['Work description'].notna() &
    df['Sanction Amount ( ₹ )'].notna()
].copy()

In [41]:
print(fuzzy_data.shape)

(77897, 35)

In [42]:
from rapidfuzz import fuzz

fuzzy_data['match_text'] = (
    fuzzy_data['Constituency_clean'] + ' ' +
    fuzzy_data['Work_description_clean']
)

In [43]:
from rapidfuzz import fuzz

def fuzzy_match(row, candidates, threshold=90):
    best_match = None
    best_score = 0

    for idx in candidates:
        score = fuzz.token_set_ratio(
            row['Work_description_clean'],
            fuzzy_data.loc[idx, 'Work_description_clean']
        )

        if score >= threshold and score > best_score:
            best_score = score
            best_match = idx

    return best_match, best_score

In [44]:
candidate_groups = fuzzy_data.groupby(
    ['Constituency_clean', 'Sanction_Amount_clean']
).groups

In [45]:
print("Number of candidate groups:", len(candidate_groups))

Number of candidate groups: 21952

In [46]:
from rapidfuzz import process, fuzz

fuzzy_data['Fuzzy_Project_ID'] = fuzzy_data['Project_ID']

for (constituency, amount), indices in candidate_groups.items():
    indices = list(indices)

    if len(indices) <= 1:
        continue

    descriptions = fuzzy_data.loc[indices, 'Work_description_clean'].to_dict()

    for idx in indices:
        current_desc = fuzzy_data.loc[idx, 'Work_description_clean']

        matches = process.extract(
            current_desc,
            descriptions,
            scorer=fuzz.token_set_ratio,
            score_cutoff=90,
            limit=10
        )

        for match_desc, score, match_idx in matches:
            if match_idx != idx:
                fuzzy_data.loc[idx, 'Fuzzy_Project_ID'] = fuzzy_data.loc[
                    match_idx, 'Project_ID'
                ]
                break

In [47]:
print(fuzzy_data['Fuzzy_Project_ID'].notna().sum())

77897

In [48]:
fuzzy_data['Fuzzy_Project_ID'] = fuzzy_data['Project_ID']

In [49]:
changed = (
    fuzzy_data['Fuzzy_Project_ID'] != fuzzy_data['Project_ID']
).sum()

print("Fuzzy matched rows:", changed)

Fuzzy matched rows: 0

In [50]:
print(
    fuzzy_data.groupby(
        ['Constituency_clean', 'Work_description_clean']
    )['Sanction Amount ( ₹ )']
    .nunique()
    .value_counts()
    .head(10)
)

Sanction Amount ( ₹ )
1     70216
2       309
3        97
4        46
5        24
7        13
6         7
10        5
8         5
9         4
Name: count, dtype: int64

In [51]:
# Find constituency + description combinations
# that have more than one sanction amount

amount_variations = (
    fuzzy_data.groupby(
        ['Constituency_clean', 'Work_description_clean']
    )['Sanction Amount ( ₹ )']
    .nunique()
)

print("Groups with multiple sanction amounts:",
      (amount_variations > 1).sum())

Groups with multiple sanction amounts: 524

In [52]:
print(
    amount_variations[amount_variations > 1]
    .head(20)
)

Constituency_clean  Work_description_clean
allahabad           solar light install in allahabad lokasabha             4
                    solar light install in allahabad loksabha              3
ambala (sc)         completion of sc choupal                               2
                    construction of bc choupal                             3
                    construction of general choupal                        2
                    construction of hall                                   3
                    construction of shed                                   5
                    construction of shed in cremation ground               2
                    construction of shed in front of bc choupal            2
                    construction of shed in front of community center      2
                    construction of shed in front of sc choupal            2
                    construction of waiting shed in cremation ground       3
                    construction of waiting shed in cremation ground.      2
amritsar            construction of dharamshala                            5
                    construction of interlocking tiles                     2
                    for const of community hall in commiittee ghar         2
                    for const of dharamshala                               3
                    for const of street and drains                         2
                    for const of street and drains (interlocking tiles)    2
                    for const of streets and drains                        2
Name: Sanction Amount ( ₹ ), dtype: int64

In [53]:
from rapidfuzz import process, fuzz

fuzzy_data['Fuzzy_Project_ID'] = fuzzy_data['Project_ID']

# Group only by constituency
candidate_groups = fuzzy_data.groupby('Constituency_clean').groups

for constituency, indices in candidate_groups.items():
    indices = list(indices)

    if len(indices) <= 1:
        continue

    descriptions = fuzzy_data.loc[
        indices, 'Work_description_clean'
    ].to_dict()

    for idx in indices:
        current_desc = fuzzy_data.loc[
            idx, 'Work_description_clean'
        ]

        current_amount = pd.to_numeric(
            fuzzy_data.loc[idx, 'Sanction Amount ( ₹ )'],
            errors='coerce'
        )

        matches = process.extract(
            current_desc,
            descriptions,
            scorer=fuzz.token_set_ratio,
            score_cutoff=90,
            limit=10
        )

        for match_desc, score, match_idx in matches:

            if match_idx == idx:
                continue

            match_amount = pd.to_numeric(
                fuzzy_data.loc[match_idx, 'Sanction Amount ( ₹ )'],
                errors='coerce'
            )

            if pd.isna(current_amount) or pd.isna(match_amount):
                continue

            amount_difference = abs(
                current_amount - match_amount
            ) / max(current_amount, match_amount)

            if amount_difference <= 0.05:
                fuzzy_data.loc[idx, 'Fuzzy_Project_ID'] = (
                    fuzzy_data.loc[match_idx, 'Project_ID']
                )
                break

In [54]:
changed = (
    fuzzy_data['Fuzzy_Project_ID'] != fuzzy_data['Project_ID']
).sum()

print("Fuzzy matched rows:", changed)

Fuzzy matched rows: 21630

In [55]:
fuzzy_matches = fuzzy_data[
    fuzzy_data['Fuzzy_Project_ID'] != fuzzy_data['Project_ID']
]

print(fuzzy_matches.shape)

(21630, 37)

In [56]:
fuzzy_matches[
    ['Constituency',
     'Work description',
     'Sanction Amount ( ₹ )',
     'Project_ID',
     'Fuzzy_Project_ID']
].head(20)

,Constituency,Work description,Sanction Amount ( ₹ ),Project_ID,Fuzzy_Project_ID
116774,DHARWAD,construction of community hall at kardigudda v...,495627.0,dharwad_construction of community hall at kard...,dharwad_construction of community bhavan at dh...
116786,DAHOD(ST),khapariya game damor faliya ma c.c.road nu kam,250000.0,dahod(st)_khapariya game damor faliya ma c.c.r...,dahod(st)_khapariiya game damor simada faliya ...
116787,DAHOD(ST),agavada game gamtal sarpanch faliya ma c.c.roa...,245697.0,dahod(st)_agavada game gamtal sarpanch faliya ...,dahod(st)_vajelav game sarpanch faliya ma c.c....
116789,DAHOD(ST),khapariiya game damor simada faliya faliya ma ...,245697.0,dahod(st)_khapariiya game damor simada faliya ...,dahod(st)_khapariya game damor faliya ma c.c.r...
116794,DAHOD(ST),nasirpur game mavi faliya ma samuhik kuva nu kam,245826.0,dahod(st)_nasirpur game mavi faliya ma samuhik...,dahod(st)_lilar game mavi faliya ma samuhik k...
116795,DAHOD(ST),punsari game bhuriya faliya ma paka rasta ne j...,245697.0,dahod(st)_punsari game bhuriya faliya ma paka ...,dahod(st)_kharva game bhuriya faliya ma c.c.ro...
116810,DAHOD(ST),lilar game mavi faliya ma samuhik kuva nu kam,245826.0,dahod(st)_lilar game mavi faliya ma samuhik k...,dahod(st)_nasirpur game mavi faliya ma samuhik...
116812,DAHOD(ST),bhutardi game bhuriya faliya ma c.c.road nu kam,247496.0,dahod(st)_bhutardi game bhuriya faliya ma c.c....,dahod(st)_kharva game bhuriya faliya ma c.c.ro...
116817,DAHOD(ST),vajelav game sarpanch faliya ma c.c.road nu kam,249291.0,dahod(st)_vajelav game sarpanch faliya ma c.c....,dahod(st)_agavada game gamtal sarpanch faliya ...
116825,DAHOD(ST),kharva game bhuriya faliya ma c.c.road nu kam,249291.0,dahod(st)_kharva game bhuriya faliya ma c.c.ro...,dahod(st)_punsari game bhuriya faliya ma paka ...
116848,FARIDKOT(SC),construction of mid day meal shed in govt prim...,300000.0,faridkot(sc)_construction of mid day meal shed...,faridkot(sc)_construction of mid day meal shed...
116849,FARIDKOT(SC),construction of mid day meal shed in govt prim...,300000.0,faridkot(sc)_construction of mid day meal shed...,faridkot(sc)_construction of mid day meal shed...
116850,FARIDKOT(SC),construction of mid day meal shed in govt prim...,300000.0,faridkot(sc)_construction of mid day meal shed...,faridkot(sc)_construction of mid day meal shed...
116851,FARIDKOT(SC),construction of mid day meal shed in govt prim...,300000.0,faridkot(sc)_construction of mid day meal shed...,faridkot(sc)_construction of mid day meal shed...
116852,FARIDKOT(SC),construction of mid day meal shed in govt prim...,300000.0,faridkot(sc)_construction of mid day meal shed...,faridkot(sc)_construction of mid day meal shed...
116853,FARIDKOT(SC),construction of mid day meal shed in govt prim...,300000.0,faridkot(sc)_construction of mid day meal shed...,faridkot(sc)_construction of mid day meal shed...
116854,FARIDKOT(SC),construction of mid day meal shed in govt prim...,299155.0,faridkot(sc)_construction of mid day meal shed...,faridkot(sc)_construction of mid day meal shed...
116855,FARIDKOT(SC),construction of mid day meal shed in govt prim...,300000.0,faridkot(sc)_construction of mid day meal shed...,faridkot(sc)_construction of mid day meal shed...
116856,FARIDKOT(SC),construction of mid day meal shed in govt prim...,300000.0,faridkot(sc)_construction of mid day meal shed...,faridkot(sc)_construction of mid day meal shed...
116858,FARIDKOT(SC),installation of ro system and water cooler in ...,84500.0,faridkot(sc)_installation of ro system and wat...,faridkot(sc)_installation of ro system and wat...

In [57]:
fuzzy_data['Fuzzy_Project_ID'] = fuzzy_data['Project_ID']

In [58]:
from rapidfuzz import process, fuzz

fuzzy_data['Fuzzy_Project_ID'] = fuzzy_data['Project_ID']

candidate_groups = fuzzy_data.groupby('Constituency_clean').groups

for constituency, indices in candidate_groups.items():
    indices = list(indices)

    if len(indices) <= 1:
        continue

    descriptions = fuzzy_data.loc[
        indices, 'Work_description_clean'
    ].to_dict()

    for idx in indices:

        current_desc = fuzzy_data.loc[
            idx, 'Work_description_clean'
        ]

        current_amount = pd.to_numeric(
            fuzzy_data.loc[idx, 'Sanction Amount ( ₹ )'],
            errors='coerce'
        )

        matches = process.extract(
            current_desc,
            descriptions,
            scorer=fuzz.token_set_ratio,
            score_cutoff=95,
            limit=10
        )

        for match_desc, score, match_idx in matches:

            if match_idx == idx:
                continue

            match_amount = pd.to_numeric(
                fuzzy_data.loc[match_idx, 'Sanction Amount ( ₹ )'],
                errors='coerce'
            )

            if pd.isna(current_amount) or pd.isna(match_amount):
                continue

            amount_difference = (
                abs(current_amount - match_amount)
                / max(current_amount, match_amount)
            )

            if amount_difference <= 0.02:

                fuzzy_data.loc[idx, 'Fuzzy_Project_ID'] = (
                    fuzzy_data.loc[match_idx, 'Project_ID']
                )

                break

In [59]:
changed = (
    fuzzy_data['Fuzzy_Project_ID'] != fuzzy_data['Project_ID']
).sum()

print("Fuzzy matched rows:", changed)

Fuzzy matched rows: 10069

In [60]:
fuzzy_matches = fuzzy_data[
    fuzzy_data['Fuzzy_Project_ID'] != fuzzy_data['Project_ID']
]

print(fuzzy_matches.shape)

print(
    fuzzy_matches[
        ['Constituency',
         'Work description',
         'Sanction Amount ( ₹ )',
         'Project_ID',
         'Fuzzy_Project_ID']
    ].head(20).to_string(index=False)
)

(10069, 37)
Constituency                                                                            Work description Sanction Amount ( ₹ )                                                                                                      Project_ID                                                                                            Fuzzy_Project_ID
FARIDKOT(SC)                     construction of mid day meal shed in govt primary school bajakhana main              300000.0                     faridkot(sc)_construction of mid day meal shed in govt primary school bajakhana main_300000                                faridkot(sc)_construction of mid day meal shed at govt primary school_299155
FARIDKOT(SC)                            construction of mid day meal shed in govt primary school gondara              300000.0                            faridkot(sc)_construction of mid day meal shed in govt primary school gondara_300000                                faridkot(sc)_construction of mid day meal shed at govt primary school_299155
FARIDKOT(SC)                    construction of mid day meal shed in govt primary school sedha singhwala              300000.0                    faridkot(sc)_construction of mid day meal shed in govt primary school sedha singhwala_300000                                faridkot(sc)_construction of mid day meal shed at govt primary school_299155
FARIDKOT(SC)                            construction of mid day meal shed in govt primary school rauwala              300000.0                            faridkot(sc)_construction of mid day meal shed in govt primary school rauwala_300000                                faridkot(sc)_construction of mid day meal shed at govt primary school_299155
FARIDKOT(SC)                     construction of mid day meal shed in govt primary school dal singh wala              300000.0                     faridkot(sc)_construction of mid day meal shed in govt primary school dal singh wala_300000                                faridkot(sc)_construction of mid day meal shed at govt primary school_299155
FARIDKOT(SC)               construction of mid day meal shed in govt primary school bajakhana (bus adda)              300000.0               faridkot(sc)_construction of mid day meal shed in govt primary school bajakhana (bus adda)_300000                                faridkot(sc)_construction of mid day meal shed at govt primary school_299155
FARIDKOT(SC)                          construction of mid day meal shed in govt primary school okandwala              299155.0                          faridkot(sc)_construction of mid day meal shed in govt primary school okandwala_299155                                faridkot(sc)_construction of mid day meal shed at govt primary school_299155
FARIDKOT(SC)                        construction of mid day meal shed in govt primary school gumti khurd              300000.0                        faridkot(sc)_construction of mid day meal shed in govt primary school gumti khurd_300000                                faridkot(sc)_construction of mid day meal shed at govt primary school_299155
FARIDKOT(SC)                         construction of mid day meal shed in govt primary school pakka no.4              300000.0                         faridkot(sc)_construction of mid day meal shed in govt primary school pakka no.4_300000                                faridkot(sc)_construction of mid day meal shed at govt primary school_299155
FARIDKOT(SC)                installation of ro system and water cooler in govt primary school pakka no.4               84500.0                 faridkot(sc)_installation of ro system and water cooler in govt primary school pakka no.4_84500                        faridkot(sc)_installation of ro system and water cooler in govt primary school_84500
FARIDKOT(SC)             installation of ro system and water cooler in govt primary school dhilwan kalan               84500.0              faridkot(sc)_installation of ro system and water cooler in govt primary school dhilwan kalan_84500                        faridkot(sc)_installation of ro system and water cooler in govt primary school_84500
FARIDKOT(SC)              installation of ro system and water cooler in govt primary school gurri sangar              100000.0              faridkot(sc)_installation of ro system and water cooler in govt primary school gurri sangar_100000                              faridkot(sc)_installation of ro and water cooler in govt primary school_100000
FARIDKOT(SC)            installation of ro system and water cooler in govt primary school bajakhana main               84500.0             faridkot(sc)_installation of ro system and water cooler in govt primary school bajakhana main_84500                        faridkot(sc)_installation of ro system and water cooler in govt primary school_84500
FARIDKOT(SC)                     installation of ro system and water cooler in govt primary school dhudi               84500.0                      faridkot(sc)_installation of ro system and water cooler in govt primary school dhudi_84500                        faridkot(sc)_installation of ro system and water cooler in govt primary school_84500
 JHANJHARPUR     khajauli hospital chowk ke pass pre fabricated  bus sheds ka kray and instolation work.             1451000.0     jhanjharpur_khajauli hospital chowk ke pass pre fabricated  bus sheds ka kray and instolation work._1451000             jhanjharpur_ranti chowk ke pass pre fabricated  bus sheds ka kray and instolation work._1451000
 JHANJHARPUR basopatti babhan dey chowk ke pass  pre fabricated  bus sheds ka kray and instolation work.             1451000.0 jhanjharpur_basopatti babhan dey chowk ke pass  pre fabricated  bus sheds ka kray and instolation work._1451000             jhanjharpur_ranti chowk ke pass pre fabricated  bus sheds ka kray and instolation work._1451000
 JHANJHARPUR                paduma chowk ke pass pre fabricated  bus sheds ka kray and instolation work.             1451000.0                jhanjharpur_paduma chowk ke pass pre fabricated  bus sheds ka kray and instolation work._1451000             jhanjharpur_ranti chowk ke pass pre fabricated  bus sheds ka kray and instolation work._1451000
 JHANJHARPUR                 ranti chowk ke pass pre fabricated  bus sheds ka kray and instolation work.             1451000.0                 jhanjharpur_ranti chowk ke pass pre fabricated  bus sheds ka kray and instolation work._1451000 jhanjharpur_khajauli hospital chowk ke pass pre fabricated  bus sheds ka kray and instolation work._1451000
 JHANJHARPUR          andhra bazar chowk ke pass pre fabricated  bus sheds ka kray and instolation work.             1451000.0          jhanjharpur_andhra bazar chowk ke pass pre fabricated  bus sheds ka kray and instolation work._1451000             jhanjharpur_ranti chowk ke pass pre fabricated  bus sheds ka kray and instolation work._1451000
 JHANJHARPUR       madhepur thana chowk ke pass  pre fabricated  bus sheds ka kray and instolation work.             1451000.0       jhanjharpur_madhepur thana chowk ke pass  pre fabricated  bus sheds ka kray and instolation work._1451000             jhanjharpur_ranti chowk ke pass pre fabricated  bus sheds ka kray and instolation work._1451000

In [61]:
fuzzy_data['Fuzzy_Project_ID'] = fuzzy_data['Project_ID']

In [62]:
fuzzy_matches = fuzzy_data[
    fuzzy_data['Fuzzy_Project_ID'] != fuzzy_data['Project_ID']
]

print("Fuzzy matches after reset:", len(fuzzy_matches))

Fuzzy matches after reset: 0

In [63]:
from rapidfuzz import fuzz

examples = [
    (
        "construction of mid day meal shed in govt primary school bajakhana main",
        "construction of mid day meal shed at govt primary school"
    ),
    (
        "construction of mid day meal shed in govt primary school bajakhana main",
        "construction of mid day meal shed in govt primary school gondara"
    )
]

for a, b in examples:
    print(fuzz.token_set_ratio(a, b))

97.24770642201835
93.33333333333333

In [64]:
project_summary = (
    fuzzy_data
    .groupby('Project_ID')
    .agg(
        Constituency=('Constituency', 'first'),
        Work_Description=('Work description', 'first'),
        Sanction_Amount=('Sanction Amount ( ₹ )', 'first'),
        Record_Count=('Project_ID', 'size')
    )
    .reset_index()
)

print(project_summary.shape)
project_summary.head()

(71796, 5)

,Project_ID,Constituency,Work_Description,Sanction_Amount,Record_Count
0,__0,,,,1
1,adilabad(st)_cc road from nytham raju (h) to n...,ADILABAD(ST),cc road from nytham raju (h) to nytham bheem r...,100000.0,1
2,adilabad(st)_cc road from salam manku (h) to d...,ADILABAD(ST),cc road from salam manku (h) to durva ramarao (h),150000.0,1
3,adilabad(st)_cc road from todasam umesh (h) to...,ADILABAD(ST),cc road from todasam umesh (h) to nytham ganap...,150000.0,1
4,adilabad(st)_cc road from vittaleshwar mandir ...,ADILABAD(ST),cc road from vittaleshwar mandir to durva shat...,100000.0,1

In [65]:
print("Total unique projects:",
      project_summary['Project_ID'].nunique())

Total unique projects: 71796

In [66]:
print("Total unique projects:",
      project_summary['Project_ID'].nunique())

Total unique projects: 71796

In [67]:
from rapidfuzz import process, fuzz

# Get unique project descriptions
unique_projects = project_summary[
    ['Project_ID', 'Constituency', 'Work_Description', 'Sanction_Amount']
].copy()

print("Unique projects:", len(unique_projects))

Unique projects: 71796

In [68]:
unique_projects['Work_Description'] = (
    unique_projects['Work_Description']
    .astype(str)
    .str.lower()
    .str.strip()
)

In [69]:
potential_matches = []

for constituency, group in unique_projects.groupby('Constituency'):
    indices = group.index.tolist()

    descriptions = group['Work_Description'].to_dict()

    for idx in indices:
        current = descriptions[idx]

        matches = process.extract(
            current,
            descriptions,
            scorer=fuzz.ratio,
            score_cutoff=95,
            limit=5
        )

        for match_text, score, match_idx in matches:
            if idx != match_idx:
                potential_matches.append({
                    'Project_ID_1': group.loc[idx, 'Project_ID'],
                    'Project_ID_2': group.loc[match_idx, 'Project_ID'],
                    'Description_1': current,
                    'Description_2': match_text,
                    'Similarity': score,
                    'Amount_1': group.loc[idx, 'Sanction_Amount'],
                    'Amount_2': group.loc[match_idx, 'Sanction_Amount']
                })

potential_matches_df = pd.DataFrame(potential_matches)

print("Potential matches:", len(potential_matches_df))

Potential matches: 13200

In [72]:
potential_matches_df['Amount_1'] = pd.to_numeric(
    potential_matches_df['Amount_1'],
    errors='coerce'
)

potential_matches_df['Amount_2'] = pd.to_numeric(
    potential_matches_df['Amount_2'],
    errors='coerce'
)

In [73]:

potential_matches_df['Amount_Difference_%'] = (
    abs(
        potential_matches_df['Amount_1'] -
        potential_matches_df['Amount_2']
    )
    / potential_matches_df[['Amount_1', 'Amount_2']].max(axis=1)
) * 100

In [74]:
strong_candidates = potential_matches_df[
    potential_matches_df['Amount_Difference_%'] <= 2
].copy()

print("Strong candidates:", len(strong_candidates))

Strong candidates: 8206

In [75]:
strong_candidates[
    [
        'Description_1',
        'Description_2',
        'Similarity',
        'Amount_1',
        'Amount_2',
        'Amount_Difference_%'
    ]
].head(20)

,Description_1,Description_2,Similarity,Amount_1,Amount_2,Amount_Difference_%
0,drilling of borewell and installation of subme...,drilling of borewell and installation of subme...,95.597484,125000.0,125000.0,0.000000
1,drilling of borewell and installation of subme...,drilling of borewell and installation of subme...,95.597484,125000.0,125000.0,0.000000
2,high mast lights at besthawada village of asif...,high mast lights at kasbawada village of asifa...,95.104895,200000.0,200000.0,0.000000
3,high mast lights at kasbawada village of asifa...,high mast lights at besthawada village of asif...,95.104895,200000.0,200000.0,0.000000
4,providing high mast lights in bc locality at bela,providing high mast lights in sc locality at bela,97.959184,500000.0,500000.0,0.000000
5,providing high mast lights in bc locality at j...,providing high mast lights in sc locality at j...,98.076923,500000.0,500000.0,0.000000
6,providing high mast lights in bc locality at m...,providing high mast lights in sc locality at m...,98.039216,375000.0,375000.0,0.000000
7,providing high mast lights in sc locality at bela,providing high mast lights in bc locality at bela,97.959184,500000.0,500000.0,0.000000
8,providing high mast lights in sc locality at j...,providing high mast lights in bc locality at j...,98.076923,500000.0,500000.0,0.000000
9,providing high mast lights in sc locality at m...,providing high mast lights in bc locality at m...,98.039216,375000.0,375000.0,0.000000
10,danilimda feedar cenal division-4 in 4 steel b...,danilimda feedar cenal division-5 in 4 steel b...,98.076923,34400.0,34400.0,0.000000
11,danilimda feedar cenal division-5 in 4 steel b...,danilimda feedar cenal division-4 in 4 steel b...,98.076923,34400.0,34400.0,0.000000
12,"ishanpur feedar cenal division-1, 4 steel benches",ishanpur feedar cenal division-2- 4 steel benches,95.918367,34400.0,34400.0,0.000000
13,ishanpur feedar cenal division-2- 4 steel benches,ishanpur feedar cenal division-3 - 4 steel be...,96.000000,34400.0,34400.0,0.000000
14,ishanpur feedar cenal division-2- 4 steel benches,"ishanpur feedar cenal division-1, 4 steel benches",95.918367,34400.0,34400.0,0.000000
15,ishanpur feedar cenal division-3 - 4 steel be...,ishanpur feedar cenal division-2- 4 steel benches,96.000000,34400.0,34400.0,0.000000
16,"vasna shahvavadi garden-1, 4 steel benches","vasna shahvavadi garden-2, 4 steel benches",97.619048,34400.0,34400.0,0.000000
17,"vasna shahvavadi garden-2, 4 steel benches","vasna shahvavadi garden-1, 4 steel benches",97.619048,34400.0,34400.0,0.000000
18,vidhansabha maharajpur ke antargat vikas khand...,vidhansabha maharajpur ke antargat vikas khand...,98.347107,526108.0,524033.0,0.394406
19,vidhansabha maharajpur ke antargat vikas khand...,vidhansabha maharajpur ke antargat vikas khand...,98.333333,526108.0,525953.0,0.029462

In [76]:
strong_candidates['Match_Status'] = 'Review'

In [77]:
print(strong_candidates['Match_Status'].value_counts())

Match_Status
Review    8206
Name: count, dtype: int64

In [79]:
df['Final_Project_ID'] = df['Project_ID']

In [80]:
print("Total rows:", len(df))
print("Unique Final Project IDs:",
      df['Final_Project_ID'].nunique())

Total rows: 297472
Unique Final Project IDs: 71796

In [81]:
project_tracking = (
    df
    .groupby('Final_Project_ID')
    .agg(
        Constituency=('Constituency', 'first'),
        Work_Description=('Work description', 'first'),
        Sanction_Amount=('Sanction Amount ( ₹ )', 'first'),

        Recommended=('Recommended date', lambda x: x.notna().any()),
        Sanctioned=('Sanction Date', lambda x: x.notna().any()),
        Expenditure=('Expenditure Date', lambda x: x.notna().any()),
        Completed=('Completion Date', lambda x: x.notna().any())
    )
    .reset_index()
)

In [82]:
project_tracking.head()

,Final_Project_ID,Constituency,Work_Description,Sanction_Amount,Recommended,Sanctioned,Expenditure,Completed
0,__0,,,,False,False,False,False
1,adilabad(st)_cc road from nytham raju (h) to n...,ADILABAD(ST),cc road from nytham raju (h) to nytham bheem r...,100000.0,True,True,False,False
2,adilabad(st)_cc road from salam manku (h) to d...,ADILABAD(ST),cc road from salam manku (h) to durva ramarao (h),150000.0,True,True,False,False
3,adilabad(st)_cc road from todasam umesh (h) to...,ADILABAD(ST),cc road from todasam umesh (h) to nytham ganap...,150000.0,True,True,False,False
4,adilabad(st)_cc road from vittaleshwar mandir ...,ADILABAD(ST),cc road from vittaleshwar mandir to durva shat...,100000.0,True,True,False,False

In [83]:
project_tracking = project_tracking[
    project_tracking['Final_Project_ID'].notna() &
    (project_tracking['Final_Project_ID'] != '__0')
].copy()

In [84]:
project_tracking = project_tracking[
    ~project_tracking['Final_Project_ID'].astype(str).str.startswith('__')
].copy()

In [85]:
print("Total projects:", len(project_tracking))
print(project_tracking.head())

Total projects: 71795
                                    Final_Project_ID  Constituency  \
1  adilabad(st)_cc road from nytham raju (h) to n...  ADILABAD(ST)
2  adilabad(st)_cc road from salam manku (h) to d...  ADILABAD(ST)
3  adilabad(st)_cc road from todasam umesh (h) to...  ADILABAD(ST)
4  adilabad(st)_cc road from vittaleshwar mandir ...  ADILABAD(ST)
5  adilabad(st)_construction common community she...  ADILABAD(ST)

                                    Work_Description Sanction_Amount  \
1  cc road from nytham raju (h) to nytham bheem r...        100000.0
2  cc road from salam manku (h) to durva ramarao (h)        150000.0
3  cc road from todasam umesh (h) to nytham ganap...        150000.0
4  cc road from vittaleshwar mandir to durva shat...        100000.0
5        construction common community shed at aloor          500000

   Recommended  Sanctioned  Expenditure  Completed
1         True        True        False      False
2         True        True        False      False
3         True        True        False      False
4         True        True        False      False
5         True        True        False      False

In [86]:
project_tracking['Progress_%'] = (
    project_tracking[
        ['Recommended', 'Sanctioned', 'Expenditure', 'Completed']
    ].sum(axis=1) / 4 * 100
)

In [87]:
print(
    project_tracking[
        ['Final_Project_ID',
         'Constituency',
         'Recommended',
         'Sanctioned',
         'Expenditure',
         'Completed',
         'Progress_%']
    ].head(10)
)

                                     Final_Project_ID  Constituency  \
1   adilabad(st)_cc road from nytham raju (h) to n...  ADILABAD(ST)
2   adilabad(st)_cc road from salam manku (h) to d...  ADILABAD(ST)
3   adilabad(st)_cc road from todasam umesh (h) to...  ADILABAD(ST)
4   adilabad(st)_cc road from vittaleshwar mandir ...  ADILABAD(ST)
5   adilabad(st)_construction common community she...  ADILABAD(ST)
6   adilabad(st)_construction of  community hall a...  ADILABAD(ST)
7   adilabad(st)_construction of  community hall a...  ADILABAD(ST)
8   adilabad(st)_construction of  road from bridge...  ADILABAD(ST)
9   adilabad(st)_construction of  road from grave ...  ADILABAD(ST)
10  adilabad(st)_construction of  road from kandel...  ADILABAD(ST)

    Recommended  Sanctioned  Expenditure  Completed  Progress_%
1          True        True        False      False        50.0
2          True        True        False      False        50.0
3          True        True        False      False        50.0
4          True        True        False      False        50.0
5          True        True        False      False        50.0
6          True        True        False      False        50.0
7          True        True        False      False        50.0
8          True        True        False      False        50.0
9          True        True        False      False        50.0
10         True        True        False      False        50.0

In [88]:
def get_status(row):
    if row['Completed']:
        return 'Completed'
    elif row['Expenditure']:
        return 'Expenditure'
    elif row['Sanctioned']:
        return 'Sanctioned'
    elif row['Recommended']:
        return 'Recommended'
    else:
        return 'Unknown'

project_tracking['Current_Status'] = project_tracking.apply(
    get_status,
    axis=1
)

In [89]:
print(
    project_tracking[
        ['Final_Project_ID',
         'Constituency',
         'Progress_%',
         'Current_Status']
    ].head(10)
)

                                     Final_Project_ID  Constituency  \
1   adilabad(st)_cc road from nytham raju (h) to n...  ADILABAD(ST)
2   adilabad(st)_cc road from salam manku (h) to d...  ADILABAD(ST)
3   adilabad(st)_cc road from todasam umesh (h) to...  ADILABAD(ST)
4   adilabad(st)_cc road from vittaleshwar mandir ...  ADILABAD(ST)
5   adilabad(st)_construction common community she...  ADILABAD(ST)
6   adilabad(st)_construction of  community hall a...  ADILABAD(ST)
7   adilabad(st)_construction of  community hall a...  ADILABAD(ST)
8   adilabad(st)_construction of  road from bridge...  ADILABAD(ST)
9   adilabad(st)_construction of  road from grave ...  ADILABAD(ST)
10  adilabad(st)_construction of  road from kandel...  ADILABAD(ST)

    Progress_% Current_Status
1         50.0     Sanctioned
2         50.0     Sanctioned
3         50.0     Sanctioned
4         50.0     Sanctioned
5         50.0     Sanctioned
6         50.0     Sanctioned
7         50.0     Sanctioned
8         50.0     Sanctioned
9         50.0     Sanctioned
10        50.0     Sanctioned

In [90]:
print(
    project_tracking['Current_Status']
    .value_counts()
)

Current_Status
Sanctioned    71795
Name: count, dtype: int64

In [92]:
stage_check = df.groupby('Project Stage').agg(
    Rows=('Project Stage', 'size'),
    Project_ID=('Project_ID', lambda x: x.notna().sum()),
    Constituency=('Constituency', lambda x: x.notna().sum()),
    Work_Description=('Work description', lambda x: x.notna().sum()),
    Sanction_Amount=('Sanction Amount ( ₹ )', lambda x: x.notna().sum()),
    Recommended_Date=('Recommended date', lambda x: x.notna().sum()),
    Sanction_Date=('Sanction Date', lambda x: x.notna().sum()),
    Expenditure_Date=('Expenditure Date', lambda x: x.notna().sum()),
    Completion_Date=('Completion Date', lambda x: x.notna().sum())
)

print(stage_check)

                 Rows  Project_ID  Constituency  Work_Description  \
Project Stage
Completed       33841           0         33841                 0
Expenditure     82367           0         82367                 0
Recommended     25634           1         25621             25059
Sanctioned     155630       77896        155630            155436

               Sanction_Amount  Recommended_Date  Sanction_Date  \
Project Stage
Completed                    0                 0              0
Expenditure                  0                 0              0
Recommended                  1             25074              0
Sanctioned               77994            155630         155630

               Expenditure_Date  Completion_Date
Project Stage
Completed                     0            33841
Expenditure               82367                0
Recommended                   0                0
Sanctioned                    0                0

In [95]:
for col in ['Work ID', 'IDA', 'WORK', 'WORK ']:
    if col in df.columns:
        print("\n", col)
        print("Non-null:", df[col].notna().sum())
        print("Unique:", df[col].nunique())

 Work ID
Non-null: 82367
Unique: 55483

 IDA
Non-null: 296915
Unique: 764

 WORK
Non-null: 102711
Unique: 77741

In [96]:
print(
    df[
        ['Work ID', 'IDA', 'WORK', 'Constituency',
         'Work description', 'Project Stage']
    ].head(20).to_string()
)

   Work ID                                           IDA WORK  Constituency Work description Project Stage
0      NaN                                           NaN  NaN           NaN              NaN   Recommended
1      NaN                                           NaN  NaN           NaN              NaN   Recommended
2      NaN                                           NaN  NaN           NaN              NaN   Recommended
3      NaN                                           NaN  NaN           NaN              NaN   Recommended
4      NaN                                           NaN  NaN           NaN              NaN   Recommended
5      NaN                                           NaN  NaN           NaN              NaN   Recommended
6      NaN                                           NaN  NaN           NaN              NaN   Recommended
7      NaN                                           NaN  NaN           NaN              NaN   Recommended
8      NaN                                           NaN  NaN           NaN              NaN   Recommended
9      NaN                                           NaN  NaN           NaN              NaN   Recommended
10     NaN                                           NaN  NaN           NaN              NaN   Recommended
11     NaN                                           NaN  NaN           NaN              NaN   Recommended
12     NaN                                           NaN  NaN           NaN              NaN   Recommended
13     NaN  ARARIA(DISTRICT PLANNING OFFICER ARARIA_IDA)  NaN        ARARIA              NaN     Completed
14     NaN    FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA)  NaN  FARIDKOT(SC)              NaN     Completed
15     NaN         KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA)  NaN        KOLLAM              NaN     Completed
16     NaN    FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA)  NaN  FARIDKOT(SC)              NaN     Completed
17     NaN    FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA)  NaN  FARIDKOT(SC)              NaN     Completed
18     NaN    FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA)  NaN  FARIDKOT(SC)              NaN     Completed
19     NaN         KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA)  NaN        KOLLAM              NaN     Completed

In [98]:
for stage in ['Recommended', 'Sanctioned', 'Expenditure', 'Completed']:
    print("\n==========", stage, "==========")

    temp = df[df['Project Stage'] == stage]

    for col in ['Work', 'WORK', 'Work Description', 'Work description',
                'Constituency', 'IDA', 'Work ID',
                'Amount Disbursed ( ₹ )',
                'Fund Disbursed Amount ( ₹ )',
                'Completion Date', 'Expenditure Date']:
        
        if col in temp.columns:
            print(
                col,
                "→ non-null:",
                temp[col].notna().sum()
            )

========== Recommended ==========
Work → non-null: 2
WORK → non-null: 25075
Work Description → non-null: 1
Work description → non-null: 25059
Constituency → non-null: 25621
IDA → non-null: 25077
Work ID → non-null: 0
Amount Disbursed ( ₹ ) → non-null: 1
Fund Disbursed Amount ( ₹ ) → non-null: 0
Completion Date → non-null: 0
Expenditure Date → non-null: 0

========== Sanctioned ==========
Work → non-null: 77994
WORK → non-null: 77636
Work Description → non-null: 0
Work description → non-null: 155436
Constituency → non-null: 155630
IDA → non-null: 155630
Work ID → non-null: 0
Amount Disbursed ( ₹ ) → non-null: 0
Fund Disbursed Amount ( ₹ ) → non-null: 0
Completion Date → non-null: 0
Expenditure Date → non-null: 0

========== Expenditure ==========
Work → non-null: 82367
WORK → non-null: 0
Work Description → non-null: 0
Work description → non-null: 0
Constituency → non-null: 82367
IDA → non-null: 82367
Work ID → non-null: 82367
Amount Disbursed ( ₹ ) → non-null: 0
Fund Disbursed Amount ( ₹ ) → non-null: 82367
Completion Date → non-null: 0
Expenditure Date → non-null: 82367

========== Completed ==========
Work → non-null: 33841
WORK → non-null: 0
Work Description → non-null: 33762
Work description → non-null: 0
Constituency → non-null: 33841
IDA → non-null: 33841
Work ID → non-null: 0
Amount Disbursed ( ₹ ) → non-null: 33746
Fund Disbursed Amount ( ₹ ) → non-null: 0
Completion Date → non-null: 33841
Expenditure Date → non-null: 0

In [99]:
for stage in ['Recommended', 'Sanctioned', 'Expenditure', 'Completed']:
    
    temp = df[
        df['Project Stage'] == stage
    ]
    
    print("\n==========", stage, "==========")
    print("Rows:", len(temp))
    print("IDA non-null:", temp['IDA'].notna().sum())
    print("Unique IDA:", temp['IDA'].nunique())
    print(
        "Duplicate IDA:",
        temp['IDA'].duplicated().sum()
    )

========== Recommended ==========
Rows: 25634
IDA non-null: 25077
Unique IDA: 675
Duplicate IDA: 24958

========== Sanctioned ==========
Rows: 155630
IDA non-null: 155630
Unique IDA: 754
Duplicate IDA: 154876

========== Expenditure ==========
Rows: 82367
IDA non-null: 82367
Unique IDA: 737
Duplicate IDA: 81630

========== Completed ==========
Rows: 33841
IDA non-null: 33841
Unique IDA: 668
Duplicate IDA: 33173

In [100]:
for stage in ['Recommended', 'Sanctioned', 'Expenditure', 'Completed']:
    
    temp = df[
        df['Project Stage'] == stage
    ]
    
    print("\n==========", stage, "==========")
    print(
        temp[['IDA', 'Constituency']]
        .dropna(subset=['IDA'])
        .head(10)
        .to_string(index=False)
    )

========== Recommended ==========
                                                                    IDA    Constituency


PURBI CHAMPARAN(DISTRICT PLANNING OFFICER MOTHIHARI EAST CHAMPARAN_IDA) PURVI CHAMPARAN
PURBI CHAMPARAN(DISTRICT PLANNING OFFICER MOTHIHARI EAST CHAMPARAN_IDA) PURVI CHAMPARAN
                                 ROHTAK(DEPUTY COMMISSIONER ROHTAK_IDA)          ROHTAK
                        Cooch Behar(DISTRICT MAGISTRATE COOCHBEHAR_IDA)  COOCHBEHAR(SC)
                        Cooch Behar(DISTRICT MAGISTRATE COOCHBEHAR_IDA)  COOCHBEHAR(SC)
                        Cooch Behar(DISTRICT MAGISTRATE COOCHBEHAR_IDA)  COOCHBEHAR(SC)
                        Cooch Behar(DISTRICT MAGISTRATE COOCHBEHAR_IDA)  COOCHBEHAR(SC)
                        Cooch Behar(DISTRICT MAGISTRATE COOCHBEHAR_IDA)  COOCHBEHAR(SC)

========== Sanctioned ==========
                                     IDA Constituency
DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA)      DHARWAD
DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA)      DHARWAD
DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA)      DHARWAD
  HAVERI(DEPUTY COMMISSIONER HAVERI_IDA)      DHARWAD
DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA)      DHARWAD
DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA)      DHARWAD
DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA)      DHARWAD
DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA)      DHARWAD
DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA)      DHARWAD
DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA)      DHARWAD

========== Expenditure ==========
                                                  IDA       Constituency
Chamarajanagar(DEPUTY COMMISSIONER CHAMARAJNAGAR_IDA) CHAMARAJANAGAR(SC)
Chamarajanagar(DEPUTY COMMISSIONER CHAMARAJNAGAR_IDA) CHAMARAJANAGAR(SC)
Chamarajanagar(DEPUTY COMMISSIONER CHAMARAJNAGAR_IDA) CHAMARAJANAGAR(SC)
Chamarajanagar(DEPUTY COMMISSIONER CHAMARAJNAGAR_IDA) CHAMARAJANAGAR(SC)
Chamarajanagar(DEPUTY COMMISSIONER CHAMARAJNAGAR_IDA) CHAMARAJANAGAR(SC)
Chamarajanagar(DEPUTY COMMISSIONER CHAMARAJNAGAR_IDA) CHAMARAJANAGAR(SC)
          GHAZIABAD(DISTRICT MAGISTRAE GHAZIABAD_IDA)          GHAZIABAD
          GHAZIABAD(DISTRICT MAGISTRAE GHAZIABAD_IDA)          GHAZIABAD
          GHAZIABAD(DISTRICT MAGISTRAE GHAZIABAD_IDA)          GHAZIABAD
                INDORE(DISTRICT COLLECTOR INDORE_IDA)             INDORE

========== Completed ==========
                                         IDA Constituency
ARARIA(DISTRICT PLANNING OFFICER ARARIA_IDA)       ARARIA
  FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA) FARIDKOT(SC)
       KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA)       KOLLAM
  FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA) FARIDKOT(SC)
  FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA) FARIDKOT(SC)
  FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA) FARIDKOT(SC)
       KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA)       KOLLAM
       KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA)       KOLLAM
  FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA) FARIDKOT(SC)
  FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA) FARIDKOT(SC)

In [101]:
comp = df[
    df['Project Stage'] == 'Completed'
].copy()

print(
    comp[
        ['Work', 'Work description',
         'Constituency', 'IDA',
         'Amount Disbursed ( ₹ )',
         'Completion Date']
    ].head(20).to_string(index=False)
)

                                                                                                                     Work Work description       Constituency                                                   IDA Amount Disbursed ( ₹ ) Completion Date
  WS/MP418/2024-2025/133409-Construction of roads, link roads, pathways or any other road with or without drainage system              NaN             ARARIA          ARARIA(DISTRICT PLANNING OFFICER ARARIA_IDA)               448127.0      2024-09-05
                                       WS/MP18152/2024-2025/133691-Construction of rooms and halls in school and colleges              NaN       FARIDKOT(SC)            FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA)               300000.0      2025-04-07
  WS/MP345/2024-2025/134140-Construction of roads, link roads, pathways or any other road with or without drainage system              NaN             KOLLAM                 KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA)               293492.0      2024-08-12
                                       WS/MP18152/2024-2025/133686-Construction of rooms and halls in school and colleges              NaN       FARIDKOT(SC)            FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA)               300000.0      2025-04-07
                                       WS/MP18152/2024-2025/133690-Construction of rooms and halls in school and colleges              NaN       FARIDKOT(SC)            FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA)               300000.0      2025-04-07
                                       WS/MP18152/2024-2025/133689-Construction of rooms and halls in school and colleges              NaN       FARIDKOT(SC)            FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA)               300000.0      2025-04-07
                                    WS/MP345/2024-2025/134143-Construction of buildings for community cultural activities              NaN             KOLLAM                 KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA)              1182588.0      2024-10-28
                                    WS/MP345/2024-2025/134144-Construction of buildings for community cultural activities              NaN             KOLLAM                 KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA)               338444.0      2024-08-17
                                       WS/MP18152/2024-2025/133694-Construction of rooms and halls in school and colleges              NaN       FARIDKOT(SC)            FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA)               300000.0      2025-04-07
                                                   WS/MP18152/2024-2025/133696-Installing community drinking water plants              NaN       FARIDKOT(SC)            FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA)                84500.0      2025-04-07
                                                   WS/MP18152/2024-2025/133701-Installing community drinking water plants              NaN       FARIDKOT(SC)            FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA)                84500.0      2025-04-07
                                       WS/MP18152/2024-2025/133693-Construction of rooms and halls in school and colleges              NaN       FARIDKOT(SC)            FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA)               300000.0      2025-04-07
                                                   WS/MP18152/2024-2025/133703-Installing community drinking water plants              NaN       FARIDKOT(SC)            FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA)                84500.0      2025-04-07
                                       WS/MP18152/2024-2025/133688-Construction of rooms and halls in school and colleges              NaN       FARIDKOT(SC)            FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA)               300000.0      2025-04-07
                                       WS/MP18152/2024-2025/133687-Construction of rooms and halls in school and colleges              NaN       FARIDKOT(SC)            FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA)               300000.0      2025-04-07
                                         WS/MP345/2024-2025/134123-Construction of rooms and halls in school and colleges              NaN             KOLLAM                 KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA)              4740188.0      2024-12-06
WS/MP18278/2024-2025/134671-Construction of roads, link roads, pathways or any other road with or without drainage system              NaN JANJGIR CHAMPA(SC) JANJGIR-CHAMPA(DISTRICT COLLECTOR JANJGIR CHAMPA_IDA)               500000.0      2024-10-08
WS/MP18278/2024-2025/134668-Construction of roads, link roads, pathways or any other road with or without drainage system              NaN JANJGIR CHAMPA(SC) JANJGIR-CHAMPA(DISTRICT COLLECTOR JANJGIR CHAMPA_IDA)              1500000.0      2024-12-06
                                 WS/\t MP620/2024-2025/133312-Construction of buildings for community cultural activities              NaN            DHARWAD              DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA)               498091.0      2025-06-09
                                 WS/\t MP620/2024-2025/133166-Construction of buildings for community cultural activities              NaN            DHARWAD              DHARWAD(DEPUTY COMMISSIONER DHARWAR_IDA)               497185.0      2024-10-14

In [102]:
print("Completed rows:", len(comp))
print("Unique Work:", comp['Work'].nunique())
print("Unique Work description:", comp['Work description'].nunique())
print("Unique IDA:", comp['IDA'].nunique())

Completed rows: 33841
Unique Work: 33841
Unique Work description: 0
Unique IDA: 668

In [104]:
exp = df[
    df['Project Stage'] == 'Expenditure'
].copy()

comp = df[
    df['Project Stage'] == 'Completed'
].copy()

# Convert both to clean strings
exp_ids = (
    exp['Work ID']
    .dropna()
    .astype(str)
    .str.strip()
)

comp_work = (
    comp['Work']
    .dropna()
    .astype(str)
    .str.strip()
)

# Check direct overlap
common_ids = set(exp_ids) & set(comp_work)

print("Expenditure Work IDs:", len(set(exp_ids)))
print("Completed Work values:", len(set(comp_work)))
print("Common Work IDs:", len(common_ids))

Expenditure Work IDs: 55483
Completed Work values: 33841
Common Work IDs: 0

In [105]:
print("EXPENDITURE")
print(
    exp[['Work ID', 'Work', 'IDA', 'Constituency',
         'Fund Disbursed Amount ( ₹ )',
         'Expenditure Date']]
    .head(10)
    .to_string(index=False)
)

print("\nCOMPLETED")
print(
    comp[['Work', 'IDA', 'Constituency',
          'Amount Disbursed ( ₹ )',
          'Completion Date']]
    .head(10)
    .to_string(index=False)
)

EXPENDITURE
                    Work ID                                                                                          Work                                                   IDA       Constituency Fund Disbursed Amount ( ₹ ) Expenditure Date
WS/MP18080/2025-2026/181959                                                 Construction of footpaths and pedestrian ways Chamarajanagar(DEPUTY COMMISSIONER CHAMARAJNAGAR_IDA) CHAMARAJANAGAR(SC)                    250000.0      20-Aug-2026
WS/MP18080/2025-2026/181962                                                 Construction of footpaths and pedestrian ways Chamarajanagar(DEPUTY COMMISSIONER CHAMARAJNAGAR_IDA) CHAMARAJANAGAR(SC)                    250000.0      20-Aug-2026
WS/MP18080/2025-2026/181818                     Construction of boundary walls of existing public and community buildings Chamarajanagar(DEPUTY COMMISSIONER CHAMARAJNAGAR_IDA) CHAMARAJANAGAR(SC)                    250000.0      20-Aug-2026
WS/MP18080/2025-2026/181801                                   Construction of buildings for community cultural activities Chamarajanagar(DEPUTY COMMISSIONER CHAMARAJNAGAR_IDA) CHAMARAJANAGAR(SC)                    250000.0      20-Aug-2026
WS/MP18080/2025-2026/181963 Construction of roads, link roads, pathways or any other road with or without drainage system Chamarajanagar(DEPUTY COMMISSIONER CHAMARAJNAGAR_IDA) CHAMARAJANAGAR(SC)                    250000.0      20-Aug-2026
WS/MP18080/2025-2026/182046                                         Construction of community centers and community halls Chamarajanagar(DEPUTY COMMISSIONER CHAMARAJNAGAR_IDA) CHAMARAJANAGAR(SC)                    125000.0      20-Aug-2026
WS/MP18218/2025-2026/233777 Construction of roads, link roads, pathways or any other road with or without drainage system           GHAZIABAD(DISTRICT MAGISTRAE GHAZIABAD_IDA)          GHAZIABAD                    799146.0      21-Aug-2026
WS/MP18218/2025-2026/233878 Construction of roads, link roads, pathways or any other road with or without drainage system           GHAZIABAD(DISTRICT MAGISTRAE GHAZIABAD_IDA)          GHAZIABAD                    832080.0      04-Aug-2026
WS/MP18218/2025-2026/233781 Construction of roads, link roads, pathways or any other road with or without drainage system           GHAZIABAD(DISTRICT MAGISTRAE GHAZIABAD_IDA)          GHAZIABAD                    498309.0      04-Aug-2026
  WS/MP650/2025-2026/242025                                                           Installing tube-wells and borewells                 INDORE(DISTRICT COLLECTOR INDORE_IDA)             INDORE                    101562.0      23-Aug-2026

COMPLETED
                                                                                                                   Work                                          IDA Constituency Amount Disbursed ( ₹ ) Completion Date
WS/MP418/2024-2025/133409-Construction of roads, link roads, pathways or any other road with or without drainage system ARARIA(DISTRICT PLANNING OFFICER ARARIA_IDA)       ARARIA               448127.0      2024-09-05
                                     WS/MP18152/2024-2025/133691-Construction of rooms and halls in school and colleges   FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA) FARIDKOT(SC)               300000.0      2025-04-07
WS/MP345/2024-2025/134140-Construction of roads, link roads, pathways or any other road with or without drainage system        KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA)       KOLLAM               293492.0      2024-08-12
                                     WS/MP18152/2024-2025/133686-Construction of rooms and halls in school and colleges   FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA) FARIDKOT(SC)               300000.0      2025-04-07
                                     WS/MP18152/2024-2025/133690-Construction of rooms and halls in school and colleges   FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA) FARIDKOT(SC)               300000.0      2025-04-07
                                     WS/MP18152/2024-2025/133689-Construction of rooms and halls in school and colleges   FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA) FARIDKOT(SC)               300000.0      2025-04-07
                                  WS/MP345/2024-2025/134143-Construction of buildings for community cultural activities        KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA)       KOLLAM              1182588.0      2024-10-28
                                  WS/MP345/2024-2025/134144-Construction of buildings for community cultural activities        KOLLAM(DISTRICT COLLECTOR KOLLAM_IDA)       KOLLAM               338444.0      2024-08-17
                                     WS/MP18152/2024-2025/133694-Construction of rooms and halls in school and colleges   FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA) FARIDKOT(SC)               300000.0      2025-04-07
                                                 WS/MP18152/2024-2025/133696-Installing community drinking water plants   FARIDKOT(DEPUTY COMMISSIONER FARIDKOT_IDA) FARIDKOT(SC)                84500.0      2025-04-07

In [106]:
print("\nExpenditure Work examples:")
print(exp['Work'].dropna().head(20).tolist())

print("\nCompleted Work examples:")
print(comp['Work'].dropna().head(20).tolist())

Expenditure Work examples:
['Construction of footpaths and pedestrian ways', 'Construction of footpaths and pedestrian ways', 'Construction of boundary walls of existing public and community buildings', 'Construction of buildings for community cultural activities', 'Construction of roads, link roads, pathways or any other road with or without drainage system', 'Construction of community centers and community halls', 'Construction of roads, link roads, pathways or any other road with or without drainage system', 'Construction of roads, link roads, pathways or any other road with or without drainage system', 'Construction of roads, link roads, pathways or any other road with or without drainage system', 'Installing tube-wells and borewells', 'Installing tube-wells and borewells', 'Lighting of public spaces', 'Lighting of public spaces', 'Lighting of public spaces', 'Lighting of public spaces', 'Lighting of public spaces', 'Lighting of public spaces', 'Lighting of public spaces', 'Lighting of public spaces', 'Lighting of public spaces']

Completed Work examples:
['WS/MP418/2024-2025/133409-Construction of roads, link roads, pathways or any other road with or without drainage system', 'WS/MP18152/2024-2025/133691-Construction of rooms and halls in school and colleges', 'WS/MP345/2024-2025/134140-Construction of roads, link roads, pathways or any other road with or without drainage system', 'WS/MP18152/2024-2025/133686-Construction of rooms and halls in school and colleges', 'WS/MP18152/2024-2025/133690-Construction of rooms and halls in school and colleges', 'WS/MP18152/2024-2025/133689-Construction of rooms and halls in school and colleges', 'WS/MP345/2024-2025/134143-Construction of buildings for community cultural activities', 'WS/MP345/2024-2025/134144-Construction of buildings for community cultural activities', 'WS/MP18152/2024-2025/133694-Construction of rooms and halls in school and colleges', 'WS/MP18152/2024-2025/133696-Installing community drinking water plants', 'WS/MP18152/2024-2025/133701-Installing community drinking water plants', 'WS/MP18152/2024-2025/133693-Construction of rooms and halls in school and colleges', 'WS/MP18152/2024-2025/133703-Installing community drinking water plants', 'WS/MP18152/2024-2025/133688-Construction of rooms and halls in school and colleges', 'WS/MP18152/2024-2025/133687-Construction of rooms and halls in school and colleges', 'WS/MP345/2024-2025/134123-Construction of rooms and halls in school and colleges', 'WS/MP18278/2024-2025/134671-Construction of roads, link roads, pathways or any other road with or without drainage system', 'WS/MP18278/2024-2025/134668-Construction of roads, link roads, pathways or any other road with or without drainage system', 'WS/\t MP620/2024-2025/133312-Construction of buildings for community cultural activities', 'WS/\t MP620/2024-2025/133166-Construction of buildings for community cultural activities']

In [107]:
comp['Extracted_Work_ID'] = (
    comp['Work']
    .astype(str)
    .str.extract(r'/(\d+)-', expand=False)
)

print(
    comp[
        ['Work', 'Extracted_Work_ID']
    ].head(20).to_string(index=False)
)

                                                                                                                     Work Extracted_Work_ID
  WS/MP418/2024-2025/133409-Construction of roads, link roads, pathways or any other road with or without drainage system              2024
                                       WS/MP18152/2024-2025/133691-Construction of rooms and halls in school and colleges              2024
  WS/MP345/2024-2025/134140-Construction of roads, link roads, pathways or any other road with or without drainage system              2024
                                       WS/MP18152/2024-2025/133686-Construction of rooms and halls in school and colleges              2024
                                       WS/MP18152/2024-2025/133690-Construction of rooms and halls in school and colleges              2024
                                       WS/MP18152/2024-2025/133689-Construction of rooms and halls in school and colleges              2024
                                    WS/MP345/2024-2025/134143-Construction of buildings for community cultural activities              2024
                                    WS/MP345/2024-2025/134144-Construction of buildings for community cultural activities              2024
                                       WS/MP18152/2024-2025/133694-Construction of rooms and halls in school and colleges              2024
                                                   WS/MP18152/2024-2025/133696-Installing community drinking water plants              2024
                                                   WS/MP18152/2024-2025/133701-Installing community drinking water plants              2024
                                       WS/MP18152/2024-2025/133693-Construction of rooms and halls in school and colleges              2024
                                                   WS/MP18152/2024-2025/133703-Installing community drinking water plants              2024
                                       WS/MP18152/2024-2025/133688-Construction of rooms and halls in school and colleges              2024
                                       WS/MP18152/2024-2025/133687-Construction of rooms and halls in school and colleges              2024
                                         WS/MP345/2024-2025/134123-Construction of rooms and halls in school and colleges              2024
WS/MP18278/2024-2025/134671-Construction of roads, link roads, pathways or any other road with or without drainage system              2024
WS/MP18278/2024-2025/134668-Construction of roads, link roads, pathways or any other road with or without drainage system              2024
                                 WS/\t MP620/2024-2025/133312-Construction of buildings for community cultural activities              2024
                                 WS/\t MP620/2024-2025/133166-Construction of buildings for community cultural activities              2024

In [108]:
exp_ids = set(
    exp['Work ID']
    .dropna()
    .astype(str)
    .str.strip()
)

completed_ids = set(
    comp['Extracted_Work_ID']
    .dropna()
    .astype(str)
    .str.strip()
)

common_ids = exp_ids & completed_ids

print("Expenditure Work IDs:", len(exp_ids))
print("Completed extracted IDs:", len(completed_ids))
print("Common Work IDs:", len(common_ids))

Expenditure Work IDs: 55483
Completed extracted IDs: 3
Common Work IDs: 0

In [109]:
print("EXPENDITURE Work ID examples:")
print(
    exp['Work ID']
    .dropna()
    .astype(str)
    .head(30)
    .tolist()
)

print("\nCOMPLETED Work examples:")
print(
    comp['Work']
    .dropna()
    .astype(str)
    .head(30)
    .tolist()
)

EXPENDITURE Work ID examples:
['WS/MP18080/2025-2026/181959', 'WS/MP18080/2025-2026/181962', 'WS/MP18080/2025-2026/181818', 'WS/MP18080/2025-2026/181801', 'WS/MP18080/2025-2026/181963', 'WS/MP18080/2025-2026/182046', 'WS/MP18218/2025-2026/233777', 'WS/MP18218/2025-2026/233878', 'WS/MP18218/2025-2026/233781', 'WS/MP650/2025-2026/242025', 'WS/MP650/2025-2026/242024', 'WS/MP18239/2025-2026/214751', 'WS/MP18239/2025-2026/214776', 'WS/MP18239/2025-2026/214778', 'WS/MP18239/2025-2026/214774', 'WS/MP18239/2025-2026/214772', 'WS/MP18239/2025-2026/214780', 'WS/MP18239/2025-2026/214638', 'WS/MP18239/2025-2026/214637', 'WS/MP18239/2025-2026/214639', 'WS/MP18239/2025-2026/214742', 'WS/MP18239/2025-2026/214643', 'WS/MP18239/2025-2026/214753', 'WS/MP18239/2025-2026/214768', 'WS/MP18239/2025-2026/214767', 'WS/MP18239/2025-2026/214761', 'WS/MP18239/2025-2026/214771', 'WS/MP18222/2025-2026/171497', 'WS/MP18222/2025-2026/184305', 'WS/MP18222/2025-2026/184282']

COMPLETED Work examples:
['WS/MP418/2024-2025/133409-Construction of roads, link roads, pathways or any other road with or without drainage system', 'WS/MP18152/2024-2025/133691-Construction of rooms and halls in school and colleges', 'WS/MP345/2024-2025/134140-Construction of roads, link roads, pathways or any other road with or without drainage system', 'WS/MP18152/2024-2025/133686-Construction of rooms and halls in school and colleges', 'WS/MP18152/2024-2025/133690-Construction of rooms and halls in school and colleges', 'WS/MP18152/2024-2025/133689-Construction of rooms and halls in school and colleges', 'WS/MP345/2024-2025/134143-Construction of buildings for community cultural activities', 'WS/MP345/2024-2025/134144-Construction of buildings for community cultural activities', 'WS/MP18152/2024-2025/133694-Construction of rooms and halls in school and colleges', 'WS/MP18152/2024-2025/133696-Installing community drinking water plants', 'WS/MP18152/2024-2025/133701-Installing community drinking water plants', 'WS/MP18152/2024-2025/133693-Construction of rooms and halls in school and colleges', 'WS/MP18152/2024-2025/133703-Installing community drinking water plants', 'WS/MP18152/2024-2025/133688-Construction of rooms and halls in school and colleges', 'WS/MP18152/2024-2025/133687-Construction of rooms and halls in school and colleges', 'WS/MP345/2024-2025/134123-Construction of rooms and halls in school and colleges', 'WS/MP18278/2024-2025/134671-Construction of roads, link roads, pathways or any other road with or without drainage system', 'WS/MP18278/2024-2025/134668-Construction of roads, link roads, pathways or any other road with or without drainage system', 'WS/\t MP620/2024-2025/133312-Construction of buildings for community cultural activities', 'WS/\t MP620/2024-2025/133166-Construction of buildings for community cultural activities', 'WS/MP672/2024-2025/136731-Lighting of public spaces', 'WS/MP18278/2024-2025/134638-Construction of common work sheds/ common covered sitting area', 'WS/MP18278/2024-2025/134644-Construction of roads, link roads, pathways or any other road with or without drainage system', 'WS/MP18278/2024-2025/134646-Construction of roads, link roads, pathways or any other road with or without drainage system', 'WS/MP18278/2024-2025/134674-Construction of roads, link roads, pathways or any other road with or without drainage system', 'WS/MP492/2024-2025/134984-Lighting of public spaces', 'WS/MP492/2024-2025/134981-Construction of bus-sheds or bus-stops', 'WS/MP18152/2024-2025/133697-Construction of rooms and halls in school and colleges', 'WS/MP347/2024-2025/138112-Construction of roads, link roads, pathways or any other road with or without drainage system', 'WS/MP18278/2024-2025/134672-Construction of roads, link roads, pathways or any other road with or without drainage system']

In [110]:
print("\nCompleted Work datatype:")
print(comp['Work'].dtype)

print("\nExpenditure Work ID datatype:")
print(exp['Work ID'].dtype)

Completed Work datatype:
object

Expenditure Work ID datatype:
object

In [111]:
print("Expenditure Work ID examples:")
print(
    exp['Work ID']
    .dropna()
    .astype(str)
    .head(30)
    .tolist()
)

print("\nCompleted Work examples:")
print(
    comp['Work']
    .dropna()
    .astype(str)
    .head(30)
    .tolist()
)

Expenditure Work ID examples:
['WS/MP18080/2025-2026/181959', 'WS/MP18080/2025-2026/181962', 'WS/MP18080/2025-2026/181818', 'WS/MP18080/2025-2026/181801', 'WS/MP18080/2025-2026/181963', 'WS/MP18080/2025-2026/182046', 'WS/MP18218/2025-2026/233777', 'WS/MP18218/2025-2026/233878', 'WS/MP18218/2025-2026/233781', 'WS/MP650/2025-2026/242025', 'WS/MP650/2025-2026/242024', 'WS/MP18239/2025-2026/214751', 'WS/MP18239/2025-2026/214776', 'WS/MP18239/2025-2026/214778', 'WS/MP18239/2025-2026/214774', 'WS/MP18239/2025-2026/214772', 'WS/MP18239/2025-2026/214780', 'WS/MP18239/2025-2026/214638', 'WS/MP18239/2025-2026/214637', 'WS/MP18239/2025-2026/214639', 'WS/MP18239/2025-2026/214742', 'WS/MP18239/2025-2026/214643', 'WS/MP18239/2025-2026/214753', 'WS/MP18239/2025-2026/214768', 'WS/MP18239/2025-2026/214767', 'WS/MP18239/2025-2026/214761', 'WS/MP18239/2025-2026/214771', 'WS/MP18222/2025-2026/171497', 'WS/MP18222/2025-2026/184305', 'WS/MP18222/2025-2026/184282']

Completed Work examples:
['WS/MP418/2024-2025/133409-Construction of roads, link roads, pathways or any other road with or without drainage system', 'WS/MP18152/2024-2025/133691-Construction of rooms and halls in school and colleges', 'WS/MP345/2024-2025/134140-Construction of roads, link roads, pathways or any other road with or without drainage system', 'WS/MP18152/2024-2025/133686-Construction of rooms and halls in school and colleges', 'WS/MP18152/2024-2025/133690-Construction of rooms and halls in school and colleges', 'WS/MP18152/2024-2025/133689-Construction of rooms and halls in school and colleges', 'WS/MP345/2024-2025/134143-Construction of buildings for community cultural activities', 'WS/MP345/2024-2025/134144-Construction of buildings for community cultural activities', 'WS/MP18152/2024-2025/133694-Construction of rooms and halls in school and colleges', 'WS/MP18152/2024-2025/133696-Installing community drinking water plants', 'WS/MP18152/2024-2025/133701-Installing community drinking water plants', 'WS/MP18152/2024-2025/133693-Construction of rooms and halls in school and colleges', 'WS/MP18152/2024-2025/133703-Installing community drinking water plants', 'WS/MP18152/2024-2025/133688-Construction of rooms and halls in school and colleges', 'WS/MP18152/2024-2025/133687-Construction of rooms and halls in school and colleges', 'WS/MP345/2024-2025/134123-Construction of rooms and halls in school and colleges', 'WS/MP18278/2024-2025/134671-Construction of roads, link roads, pathways or any other road with or without drainage system', 'WS/MP18278/2024-2025/134668-Construction of roads, link roads, pathways or any other road with or without drainage system', 'WS/\t MP620/2024-2025/133312-Construction of buildings for community cultural activities', 'WS/\t MP620/2024-2025/133166-Construction of buildings for community cultural activities', 'WS/MP672/2024-2025/136731-Lighting of public spaces', 'WS/MP18278/2024-2025/134638-Construction of common work sheds/ common covered sitting area', 'WS/MP18278/2024-2025/134644-Construction of roads, link roads, pathways or any other road with or without drainage system', 'WS/MP18278/2024-2025/134646-Construction of roads, link roads, pathways or any other road with or without drainage system', 'WS/MP18278/2024-2025/134674-Construction of roads, link roads, pathways or any other road with or without drainage system', 'WS/MP492/2024-2025/134984-Lighting of public spaces', 'WS/MP492/2024-2025/134981-Construction of bus-sheds or bus-stops', 'WS/MP18152/2024-2025/133697-Construction of rooms and halls in school and colleges', 'WS/MP347/2024-2025/138112-Construction of roads, link roads, pathways or any other road with or without drainage system', 'WS/MP18278/2024-2025/134672-Construction of roads, link roads, pathways or any other road with or without drainage system']

In [112]:
print(
    "Expenditure years:",
    exp['Work ID'].astype(str).str.extract(
        r'/(20\d{2}-20\d{2})/'
    )[0].value_counts()
)

print(
    "\nCompleted years:",
    comp['Work'].astype(str).str.extract(
        r'/(20\d{2}-20\d{2})/'
    )[0].value_counts()
)

Expenditure years: 0
2025-2026    56624
2024-2025    19730
2026-2027     6012
Name: count, dtype: int64

Completed years: 0
2025-2026    22790
2024-2025    10568
2026-2027      483
Name: count, dtype: int64

In [113]:
# ==========================================
# STOP POINT - SAVE CURRENT PROJECT STATE
# ==========================================

# Save the main merged dataset
df.to_csv("merged_df_stop.csv", index=False)

# Save unique project summary
project_summary.to_csv("project_summary_stop.csv", index=False)

# Save fuzzy candidates for later review
potential_matches_df.to_csv("potential_matches_stop.csv", index=False)

# Save strong candidates
strong_candidates.to_csv("strong_candidates_stop.csv", index=False)

# Save current project tracking
project_tracking.to_csv("project_tracking_stop.csv", index=False)

print("================================")
print("WORK SAVED SUCCESSFULLY")
print("================================")

print("Merged rows:", len(df))
print("Unique projects:", project_summary['Project_ID'].nunique())
print("Potential fuzzy matches:", len(potential_matches_df))
print("Strong candidates:", len(strong_candidates))
print("Project tracking rows:", len(project_tracking))

print("\nSTOP POINT REACHED.")
print("Do not run further matching code.")

================================
WORK SAVED SUCCESSFULLY
================================
Merged rows: 297472
Unique projects: 71796
Potential fuzzy matches: 13200
Strong candidates: 8206
Project tracking rows: 71795

STOP POINT REACHED.
Do not run further matching code.

In [114]:
half_completed = project_tracking[
    (project_tracking['Sanctioned'] == True) &
    (project_tracking['Expenditure'] == False) &
    (project_tracking['Completed'] == False)
]

print("Half-completed projects:", len(half_completed))

Half-completed projects: 71795

,Final_Project_ID,Constituency,Progress_%,Current_Status
1,adilabad(st)_cc road from nytham raju (h) to n...,ADILABAD(ST),50.0,Sanctioned
2,adilabad(st)_cc road from salam manku (h) to d...,ADILABAD(ST),50.0,Sanctioned
3,adilabad(st)_cc road from todasam umesh (h) to...,ADILABAD(ST),50.0,Sanctioned
4,adilabad(st)_cc road from vittaleshwar mandir ...,ADILABAD(ST),50.0,Sanctioned
5,adilabad(st)_construction common community she...,ADILABAD(ST),50.0,Sanctioned
6,adilabad(st)_construction of community hall a...,ADILABAD(ST),50.0,Sanctioned
7,adilabad(st)_construction of community hall a...,ADILABAD(ST),50.0,Sanctioned
8,adilabad(st)_construction of road from bridge...,ADILABAD(ST),50.0,Sanctioned
9,adilabad(st)_construction of road from grave ...,ADILABAD(ST),50.0,Sanctioned
10,adilabad(st)_construction of road from kandel...,ADILABAD(ST),50.0,Sanctioned
11,adilabad(st)_construction of road from lingur...,ADILABAD(ST),50.0,Sanctioned
12,adilabad(st)_construction of road from madhav...,ADILABAD(ST),50.0,Sanctioned
13,adilabad(st)_construction of additional rooms ...,ADILABAD(ST),50.0,Sanctioned
14,adilabad(st)_construction of additional rooms ...,ADILABAD(ST),50.0,Sanctioned
15,adilabad(st)_construction of additional rooms ...,ADILABAD(ST),50.0,Sanctioned
16,adilabad(st)_construction of addl. room at pre...,ADILABAD(ST),50.0,Sanctioned
17,adilabad(st)_construction of cc drain at mahil...,ADILABAD(ST),50.0,Sanctioned
18,adilabad(st)_construction of cd work on road f...,ADILABAD(ST),50.0,Sanctioned
19,adilabad(st)_construction of common community ...,ADILABAD(ST),50.0,Sanctioned
20,adilabad(st)_construction of common community ...,ADILABAD(ST),50.0,Sanctioned